### ISSUE TITLE
实验结果相关疑问

### ISSUE THREAD

**Issue by onbncbjocp68898** [percent4/embedding_rerank_retrieval#1]
请问文档中说的结果 是用的doc_qa_test.json 评测的还是 doc_qa_dataset.json？这两个数据有什么区别？

**Comment by percent4** [comment]
评测用的是doc_qa_test.json。doc_qa_test.json 在doc_qa_dataset.json的基础上加入了与日本半导体无关的文档片段。原计划doc_qa_dataset.json只是作为临时过渡的数据集使用。
