### ISSUE TITLE
train_corpus.json内容

### ISSUE THREAD

**Issue by FrozenZero** [percent4/embedding_rerank_retrieval#3]
对于embedding_finetune/embedding_fine_tuning.ipynb，我有疑问：
在Embedding finetune的时候，请教下train_corpus.json内容是怎么构建的呢?  
比如我要对1000个文档做RAG增强，那么我要做Embedding finetune就要将这1000个文档放入train_corpus.json中 ，然后去微调。最后在将其作为Embedding的模型来配合做RAG么？

**Comment by percent4** [comment]
微调的数据需要结合你自己本身的需求来定，数据量越多越好，这方面我的经验也不是很足，可以持续讨论。

**Comment by cristianohello** [comment]
@percent4 
意思是：如何生成j微调向量模型的son数据？直接通过txt文件生成的json微调数据质量高吗？

**Comment by sevenandseven** [comment]
> 对于embedding_finetune/embedding_fine_tuning.ipynb，我有疑问： 在Embedding finetune的时候，请教下train_corpus.json内容是怎么构建的呢? 比如我要对1000个文档做RAG增强，那么我要做Embedding finetune就要将这1000个文档放入train_corpus.json中 ，然后去微调。最后在将其作为Embedding的模型来配合做RAG么？


你好，关于数据这一方面我也有疑问，请问这个数据该怎么制作，node这些怎么编写呢？
