### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by Suiji12** [percent4/embedding_rerank_retrieval#5]
FileNotFoundError: [Errno 2] No such file or directory: 'D:/githubdaima/embedding_rerank_retrieval/data/queries_bce_embedding.npy'

**Comment by percent4** [comment]
需要自己调用bce_embedding模型，生成queries_bce_embedding.npy文件，这是本项目的离线部分。

**Comment by Suiji12** [comment]
好的多谢您。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月18日 16:44 |
| 收件人 | percent4/embedding_rerank_retrieval ***@***.***> |
| 抄送人 | Suiji12 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [percent4/embedding_rerank_retrieval] 缺少文件 (Issue #5) |

需要自己调用bce_embedding模型，生成queries_bce_embedding.npy文件，这是本项目的离线部分。
