### ISSUE TITLE
数据集产生

### ISSUE THREAD

**Issue by sevenandseven** [percent4/embedding_rerank_retrieval#9]
你好，我想请问一下，看你的代码里是制作数据集时：
是先通过将txt文件进行划分，划分之后每一行是一个问题，然后将问题送入到大模型中，制作答案。

这种情况做出来的数据和我直接将整个文档送入到大模型中去提取问答对，那种效果会更好一点？

**Comment by percent4** [comment]
整个文档送入大模型效果自然是最好的，但是一般大模型都是有输入长度限制的，因此，会选择将整个文档划分为chunk，然后进行问答，这也是RAG所需要解决的问题。
